[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.3"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.24.2", features = ["full"] }
pockety = { path = "../../../pockety" }